name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Optional: Add build step here if using a static site generator
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload the root directory (or your build directory)
          path: './public/'
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2