name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: Add your build steps here if using a static site generator
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"  # Or your build directory (e.g., "./dist", "./public")

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2